import { ICONS } from './icons.generated'

/**
 * Icon. Solar Linear set only, generated by `npm run icons`.
 *
 * Solar Linear icons are stroke drawings on `currentColor`, so `color` sets the
 * CSS colour rather than a fill. Sizes are the Billease icon/size tokens.
 *
 * An unknown name renders a visible label instead of failing silently, so a
 * typo shows up on the page.
 */
const SIZES = {
  xs: 'var(--icon-size-xs)',   // 16
  sm: 'var(--icon-size-sm)',   // 20
  md: 'var(--icon-size-md)',   // 24
  lg: 'var(--icon-size-lg)',   // 32
  xl: 'var(--icon-size-xl)',   // 40
  '2xl': 'var(--icon-size-2xl)', // 48
}

export default function Icon({ name, size = 'sm', color = 'currentColor', style, ...rest }) {
  const icon = ICONS[name]
  const px = SIZES[size] ?? SIZES.sm

  if (!icon) {
    return (
      <span
        className="body-xxs-regular"
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          color: 'var(--text-subtle)',
          border: 'var(--border-width-xs) dashed var(--border-bold)',
          borderRadius: 'var(--radius-sm)',
          padding: '0 var(--space-100)',
          whiteSpace: 'nowrap',
          flexShrink: 0,
          ...style,
        }}
      >
        {name}
      </span>
    )
  }

  return (
    <svg
      width={px}
      height={px}
      viewBox={icon.viewBox}
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      focusable="false"
      style={{ flexShrink: 0, display: 'block', color, ...style }}
      dangerouslySetInnerHTML={{ __html: icon.body }}
      {...rest}
    />
  )
}
